name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run : make -C 3_Implimentation/  all
    - name: run
      run : make -C 3_Implimentation/  run

