name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: coverage
      run : make -C 3_Implimentation/  coverage
    - name: test
      run : make -C 3_Implimentation/  test
