name: cpp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cppcheck
      run : sudo apt-get install cppcheck
    - name: cpp
      run  : make -C 3_Implimentation/  cpp
